BlogDemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("auth/", include("appauth.urls")),
]

appauth/urls.py
from django.urls import path
from . import views

app_name = "appauth"

urlpatterns = [
    path("login", views.applogin, name="login"),
    path("register", views.register, name="register"),
    path("captcha", views.send_email_captcha, name="send_captcha"),
    path("logout", views.applogout, name="logout"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("blog/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("create", views.create_blog, name="create_blog"),
    path("comment", views.comment, name="comment"),
    path("search", views.search, name="search")
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Blog Category
class BlogCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Blog Categories"


# Blog Posts
class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return self.title

# Comments
class BlogComment(models.Model):
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return self.content

blog/forms.py
from django import forms

from blog.models import BlogCategory


class CreateBlogForm(forms.Form):
    title = forms.CharField(max_length=200, min_length=2)
    content = forms.CharField(min_length=2)
    category = forms.IntegerField()

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, reverse, redirect
from django.urls.base import reverse_lazy
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.http.response import JsonResponse
from django.db.models import Q

from .models import *
from .forms import *

# Create your views here.

def index(request):

    blogs = Blog.objects.all().order_by("-created_time")

    return render(request, "blog/index.html", {
        "blogs":blogs
    })


def blog_detail(request, blog_id):

    try:
        blog = Blog.objects.get(pk=blog_id)
    except Exception as e:
        blog = None

    return render(request, "blog/blog_detail.html", {
        "blog": blog
    })

@login_required(login_url=reverse_lazy("appauth:login"))
@require_http_methods(["GET", "POST"])
def create_blog(request):

    if request.method == "GET":
        categories = BlogCategory.objects.all()

        return render(request, "blog/create_blog.html", {
            "categories": categories,
        })

    else:
        form = CreateBlogForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data.get("title")
            content = form.cleaned_data.get("content")
            category_id = form.cleaned_data.get("category")

            category = BlogCategory.objects.get(id=category_id)

            blog = Blog.objects.create(
                title=title,
                content=content,
                category=category,
                author=request.user
            )

            return JsonResponse({
                "code": 200,
                "message": "successfully created blog",
                "data": {
                    "blog_id": blog.id
                }
            }, status=200)

        else:
            print(form.errors)
            return JsonResponse({
                "code": 400,
                "message": "form invalid",
            }, status=400)



@login_required()
@require_POST
def comment(request):

    blog_id = request.POST.get("blog_id")
    comment_content = request.POST.get("content")

    BlogComment.objects.create(
        content=comment_content,
        blog_id=blog_id,
        author=request.user
    )

    return redirect(reverse("blog:blog_detail", kwargs={"blog_id":blog_id}))


@require_GET
def search(request):
    q = request.GET.get("q")

    blogs = Blog.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))

    return render(request, "blog/index.html", {
        "blogs": blogs
    })

templates/blog/blog_detail.html
{% extends "blog/layout.html" %}

{% load static %}

{% block title %}
    Blog Detail
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/default.min.css' %}">
    <script src="{% static 'highlight/highlight.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div>
        <img src="{% static 'image/avatar.webp' %}" alt="" class="rounded-circle" style="width: 30px; height: 30px">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">Posted at: {{ blog.created_time|date:"d-m-Y h:i A" }}</span>
    </div>
    <hr>

    <div class="py-2">
        {{ blog.content|safe }}
    </div>

    <hr>

    <div class="mt-2">
        <h3>Comment {{ blog.comments.all|length }}</h3>
        <form action="{% url 'blog:comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="Enter your comment" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">Post</button>
            </div>

        </form>

    </div>

    <div class="mt-2">
        <ul class="list-group list-group-flush">


            {% for comment in blog.comments.all %}
                <li class="list-group-item mb-3">
                    <div class="d-flex justify-content-between">
                        <div class="user-info">
                            <img src="{% static 'image/avatar.webp' %}" alt="" class="rounded-circle" style="width: 40px; height: 40px">
                            <span class="ms-2">{{ comment.author.username }}</span>
                        </div>
                        <div class="created-time align-self-center">{{ comment.created_time|date:"d-m-Y h:i A" }}</div>
                    </div>
                    <div class="mt-2">
                        {{ comment.content }}
                    </div>
                </li>
            {% endfor %}



        </ul>
    </div>

    <script>hljs.highlightAll();</script>
{% endblock %}

templates/blog/create_blog.html
{% extends "blog/layout.html" %}
{% load static %}

{% block title %}
    Post Blog
{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link href="{% static 'wangeditor/style.css' %}" rel="stylesheet">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/create_blog.js' %}"></script>

    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* If you need */
        }
        #toolbar-container { border-bottom: 1px solid #ccc; }
        #editor-container { height: 500px; }
    </style>
{% endblock %}

{% block main %}
    <h1>Create Blog</h1>
    <div class="mt-3">
        <form action="" method="POST">

            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label" for="form-title">Post Title</label>
                <input type="text" name="title" class="form-control" id="form-title">
            </div>

            <div class="mb-3">
                <label class="form-label" for="form-category">Category</label>
                <select name="category" class="form-select" id="form-category">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label">Content</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- toolbar --></div>
                    <div id="editor-container"><!-- editor --></div>
                </div>
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" id="submit-btn">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/blog/index.html
{% extends "blog/layout.html" %}

{% load static %}

{% block title %}
    Home Page
{% endblock %}


{% block main %}
    <h1>All Blogs</h1>
    <div class="row row-cols-2 row-gap-4">

        {% for blog in blogs %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 120px">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                </div>

                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/avatar.webp' %}" alt="" class="rounded-circle" style="width: 30px; height: 30px">
                        {{ blog.author.username }}
                    </div>
                    <div>
                        Posted at: {{ blog.created_time|date:"d-m-Y h:i A" }}
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}



    </div>
{% endblock %}

templates/blog/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'bootstrap5/bootstrap.min.css' %}" rel="stylesheet"></link>
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body>

<!--Navigation Bar-->
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static '' %}" height="40" alt="logo">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:index' %}" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="{% url 'blog:create_blog' %}" class="nav-link px-2 text-secondary">Create Blog</a></li>
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="GET">
                <input type="search" class="form-control form-control-light text-bg-light"
                       placeholder="Search..." aria-label="Search" name="q">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end"><a href="#"
                                                  class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                                                  data-bs-toggle="dropdown" aria-expanded="false"> <img
                        src="{% static 'image/avatar.webp' %}" alt="user-profile-pic" width="32" height="32" class="rounded-circle"> </a>
                    <ul class="dropdown-menu text-small">
                        <li><a class="dropdown-item" href="{% url 'appauth:logout' %}">Sign out</a></li>
                    </ul>
                </div>

                {% else %}

                <div class="text-end">
                    <a href="{% url 'appauth:login' %}" type="button" class="btn btn-outline-dark me-2">Login</a>
                    <a href="{% url 'appauth:register' %}" type="button" class="btn btn-warning">Sign-up</a>
                </div>

            {% endif %}



        </div>
    </div>
</header>

<main class="container bg-white p-3 rounded-3">
    {% block main %}
    {% endblock %}
</main>


</body>
</html>

templates/blog/login.html
{% extends "blog/layout.html" %}

{% load static %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>Login</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label" for="email">Email</label>
                <input type="email" class="form-control" name="email" placeholder="Email" id="email">
            </div>

            <div class="mb-3">
                <label class="form-label" for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Password" id="password">
            </div>

            <div class="mb-3 form-check">
                <label class="form-check-label" for="remember">Remember me</label>
                <input class="form-check-input" type="checkbox" value="1" id="remember">
            </div>

            <div class="mb-3">
                <button class="btn btn-primary w-100">Login</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/blog/register.html
{% extends "blog/layout.html" %}

{% load static %}

{% block title %}
    Register
{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1>Register</h1>
        <form action="" method="POST">

            {% csrf_token %}

            <div class="mb-3">
                <label class="form-label" for="username">Username</label>
                <input type="text" class="form-control" name="username" placeholder="Username" id="username">
            </div>

            <div class="mb-3">
                <label class="form-label" for="email">Email</label>
                <input type="email" class="form-control" name="email" placeholder="Email" id="email">
            </div>


            <div class="mb-3">
                <label class="form-label" for="verification">Verification Code</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Verification Code" id="verification" name="captcha">
                    <button class="btn btn-outline-secondary" type="button" id="captcha-btn">Get Code</button>
                </div>
            </div>



            <div class="mb-3">
                <label class="form-label" for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Password" id="password">
            </div>


            <div class="mb-3">
                <button class="btn btn-primary w-100">Register</button>
            </div>
        </form>
    </div>
{% endblock %}